/**
 * @author John Shields
 * @app Repota
 * @title JobReport Model - OpenAPI spec version: 1.0.0
 * @desc Model for creating and updating reports.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JobReport {
    jobReportId?: number;
    date?: string;
    vehicleModel?: string;
    vehicleReg?: string;
    milesOnVehicle?: number;
    vehicleLocation?: string;
    warranty?: number;
    breakdown?: number;
    customerName?: string;
    complaint?: string;
    cause?: string;
    correction?: string;
    parts?: string;
    workHours?: number;
    workerName?: string;
    jobComplete?: number;
}
