/*
 * Horton Golang Server
 * John Shields
 *
 * Main function to start server
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "github.com/GIT_USER_ID/GIT_REPO_ID/go"
	_ "github.com/gin-gonic/gin"
	"log"
)

// CORS are set up in ./go/routers.go
func main() {
	router := sw.NewRouter()
	log.Println("Horton started on: http://horton.eu-west-1.elasticbeanstalk.com") // AWS Elastic Beanstalk
	router.Run()
}
