/*
 * Horton
 * John Shields
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Error struct {
	Code int32 `json:"code"`

	Messages string `json:"messages"`
}
