/*
 * John Shields
 * Horton - API version: 1.0.0
 *
 * Session Model
 * Model for session token and expiry time.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Session struct {
	Token  string
	Expiry int
}
