/**
 * @author John Shields
 * @app Repota
 * @title InLineObject Model - OpenAPI spec version: 1.0.0
 * @desc Model for user details.
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineObject {
    username?: string;
    name?: string;
    password?: string;
}
