/*
 * Horton Golang Server
 * John Shields
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */
package openapi

import (
	"database/sql"
	"github.com/gin-gonic/gin"
	_ "github.com/go-sql-driver/mysql"
	"net/http"
)

func dbConn() (db *sql.DB) {
	//dbDriver := "mysql"
	//dbUser := "root"
	//dbPass := ""
	//dbName := "repotadb"
	//db, err := sql.Open(dbDriver, dbUser+":"+dbPass+"@/"+dbName)
	//db, err := sql.Open("mysql", "john:root@tcp(127.0.0.1:3306)/repotadb") // server
	db, err := sql.Open("mysql", "john:local@tcp(127.0.0.1:3306)/repotadb") // local

	if err != nil {
		panic(err.Error())
	}
	return db
}

// CreateReport - Create a report
func CreateReport(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteReport - Delete a Job Report
func DeleteReport(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetReport - Get a job report
func GetReport(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetReports - List All report
func GetReports(c *gin.Context) {
	db := dbConn()

	selDB, err := db.Query("SELECT * FROM jobReports")
	if err != nil {
		panic(err.Error())
	}

	rep := JobReport{}
	res := []JobReport{}

	for selDB.Next() {
		var id int32
		var timeDate string
		var location string
		var vehicle string
		var desc string
		var solu string

		err = selDB.Scan(&id, &timeDate, &location, &vehicle, &desc, &solu)

		if err != nil {
			panic(err.Error())
		}

		rep.Id = id
		rep.TimeDate = timeDate
		rep.Location = location
		rep.Vehicle = vehicle
		rep.Description = desc
		rep.Solution = solu
		res = append(res, rep)
	}

	defer db.Close()

	c.JSON(http.StatusOK, res)
}

// UpdateReport - Update a job report
func UpdateReport(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
