/*
 * Horton
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CustomerReport struct {

	JobReportId int32 `json:"jobReportId,omitempty"`

	TimeDate string `json:"timeDate,omitempty"`

	VehicleModel string `json:"vehicleModel,omitempty"`

	VehicleReg string `json:"vehicleReg,omitempty"`

	MilesOnVehicle int32 `json:"milesOnVehicle,omitempty"`

	VehicleLocation string `json:"vehicleLocation,omitempty"`

	Warranty string `json:"warranty,omitempty"`

	Breakdown string `json:"breakdown,omitempty"`

	CustomerName string `json:"customerName,omitempty"`

	CustomerComplaint string `json:"customerComplaint,omitempty"`

	Cause string `json:"cause,omitempty"`

	Correction string `json:"correction,omitempty"`

	Parts string `json:"parts,omitempty"`

	WorkHours int32 `json:"workHours,omitempty"`

	WorkerName string `json:"workerName,omitempty"`
}
