/*
 * Horton Golang Server
 * John Shields
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobReport struct {
	Id int32 `json:"id,omitempty"`

	TimeDate string `json:"timeDate,omitempty"`

	Location string `json:"location,omitempty"`

	Vehicle string `json:"vehicle,omitempty"`

	Description string `json:"description,omitempty"`

	Solution string `json:"solution,omitempty"`
}
