/*
 * Horton
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobReport struct {
	JobReportId int32 `json:"jobReportId,omitempty"`

	WorkerId int32 `json:"workerId,omitempty"`

	WorkDoneId int32 `json:"workDoneId,omitempty"`

	TimeDate string `json:"timeDate,omitempty"`

	VehicleModel string `json:"vehicleModel,omitempty"`

	VehicleReg string `json:"vehicleReg,omitempty"`

	VehicleLocation string `json:"vehicleLocation,omitempty"`

	MilesOnVehicle int32 `json:"milesOnVehicle,omitempty"`

	Warranty string `json:"warranty,omitempty"`

	Breakdown string `json:"breakdown,omitempty"`
}
