/*
 * Horton
 * John Shields
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject struct {

	Username string `json:"username,omitempty"`

	Name string `json:"name,omitempty"`

	Password string `json:"password,omitempty"`
}
