/*
 * John Shields
 * Horton
 *
 * In line Object Model
 * User details
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject struct {
	Username string `json:"username,omitempty"`

	Name string `json:"name,omitempty"`

	Password string `json:"password,omitempty"`
}
